version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tajnehaslo
      MYSQL_DATABASE: DB_MOVIES
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  movieapp:
    build: .
    ports:
     - 8080:8080
    restart: on-failure
    depends_on:
      - db
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/DB_MOVIES"
      spring.datasource.username: 'root'
      spring.datasource.password: 'tajnehaslo'