server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
  tomcat:
    uri-encoding: UTF-8
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    encoding: UTF-8
logging:
  level:
    org:
      hibernate:
        type: TRACE


jwt:
  secret_key: secretpassword
  login_token_expiration_time: 600000


